openapi: 3.0.0
info:
  title: My API
  version: 1.0.0
paths:
  /hello:
    get:
      summary: testing service
      responses:
        "200":
          description: returns greeting
  /users:
    get:
      summary: Get all users
      responses:
        "200":
          description: Success
    post:
      summary: Create a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - email
              properties:
                name:
                  type: string
                email:
                  type: string
      responses:
        "201":
          description: User created
        "400":
          description: Invalid input
  /users/{id}:
    get:
      summary: Get a user by ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the user
          schema:
            type: integer
      responses:
        "200":
          description: User found
        "404":
          description: User not found
    put:
      summary: Update user details
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
      responses:
        "200":
          description: User updated
        "404":
          description: User not found
    delete:
      summary: Delete a user
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "204":
          description: User deleted
        "404":
          description: User not found
components: {}
tags: []
