name: Test and Deploy to Vercel

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Newman
        run: npm install -g newman

      - name: Install Newman html reporter
        run: npm install -g newman-reporter-html

      - name: Run API Tests
        run: newman run postman-tests/User-API-tst.postman_collection.json -e postman-tests/prod-environment.json

  deploy:
    needs: test # Run deployment only if tests pass
    runs-on: ubuntu-latest

    # steps:
    #   - name: Trigger Render Deployment
    #     run: |
    #       curl -X POST "$RENDER_DEPLOY_HOOK"
    #     env:
    #       RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        run: |
          vercel --prod --yes --token ${{ secrets.VERCEL_TEST_API }} \
                 --org-id ${{ secrets.VERCEL_ORG_ID }} \
                 --project-id ${{ secrets.VERCEL_PROJECT_ID }}
